/* Generated by scripts/generate_capabilities.py; edit capabilities/engines.json. */
#if (defined(ADDONS)) && (defined(KDTREE2BALLSMPI))
if (strcmp(method_str, "kdtree-2balls-mpi") == 0) *method_int = 198;
#endif
