/* Generated by scripts/generate_capabilities.py; edit capabilities/engines.json. */
#if (defined(ADDONS)) && (defined(KDTREESHEARSPHERE2BALLSMPI))
if (strcmp(method_str, "kdtree-shear-sphere-2balls-mpi") == 0) *method_int = 204;
#endif
