/* Generated by scripts/generate_capabilities.py; edit capabilities/engines.json. */
#if (defined(ADDONS)) && (defined(OCTREESHEARSPHERE2BALLSOMP))
if (strcmp(method_str, "octree-shear-sphere-2balls-omp") == 0) *method_int = 200;
#endif
