/* Generated by scripts/generate_capabilities.py; edit capabilities/engines.json. */
#if (defined(ADDONS)) && (defined(BALLTREEOMP) || defined(BALLTREEMPI))
if (strcmp(method_str, "balltree-omp") == 0) *method_int = 167;
#endif
#if (defined(ADDONS)) && (defined(BALLTREEOMP) || defined(BALLTREEMPI)) && (defined(BALLTREEMPI))
if (strcmp(method_str, "balltree-mpi") == 0) *method_int = 168;
#endif
