/* Generated by scripts/generate_capabilities.py; edit capabilities/engines.json. */
#if (defined(ADDONS)) && (defined(OCTREESHEAROMP))
if (strcmp(method_str, "octree-shear-omp") == 0) *method_int = 173;
#endif
