/* Generated by scripts/generate_capabilities.py; edit capabilities/engines.json. */
#if (defined(ADDONS)) && (defined(NEIGHBORBOXESOMP))
if (strcmp(method_str, "neighbor-boxes-omp") == 0) *method_int = 73;
#endif
