/* Generated by scripts/generate_capabilities.py; edit capabilities/engines.json. */
#if (defined(ADDONS)) && (defined(BALLTREESHEARSPHERE2BALLSMPI))
if (strcmp(method_str, "balltree-shear-sphere-2balls-mpi") == 0) *method_int = 205;
#endif
