/* Generated by scripts/generate_capabilities.py; edit capabilities/engines.json. */
#if (defined(ADDONS)) && (defined(KDTREEBOXOMP))
if (strcmp(method_str, "kdtree-box-omp") == 0) *method_int = 71;
#endif
