/* Generated by scripts/generate_capabilities.py; edit capabilities/engines.json. */
#if (defined(ADDONS)) && (defined(KDTREE2BALLSOMP))
if (strcmp(method_str, "kdtree-2balls-omp") == 0) *method_int = 197;
#endif
