/* Generated by scripts/generate_capabilities.py; edit capabilities/engines.json. */
#if (defined(ADDONS)) && (defined(OCTREEGGGOMP))
if (strcmp(method_str, "octree-ggg-omp") == 0) *method_int = 66;
#endif
