/* Generated by scripts/generate_capabilities.py; edit capabilities/engines.json. */
#if (defined(ADDONS)) && (defined(BALLTREE2BALLSMPI))
if (strcmp(method_str, "balltree-2balls-mpi") == 0) *method_int = 179;
#endif
