/* Generated by scripts/generate_capabilities.py; edit capabilities/engines.json. */
#if (defined(ADDONS)) && (defined(BALLTREE2BALLSOMP))
if (strcmp(method_str, "balltree-2balls-omp") == 0) *method_int = 174;
#endif
