# Run from the cTreeBalls project root.
searchMethod = lya-2pcf-3pcf-mpi
infile = addons/lya_forest_mpi/example_catalog.txt
infileformat = lya-ascii
iCatalogs = 1
rootDir = Output_lya_mpi
numberThreads = 2
usePeriodic = false
useLogHist = false
rangeN = 30
rminHist = 0.1
sizeHistN = 4
lya2RpMax = 30
lya2RtMax = 30
lya2RpBins = 5
lya2RtBins = 6
lya3RMax = 30
lya3RBins = 4
lya3ThetaBins = 5
lya3MuBins = 6
verbose = 1
verbose_log = 0
