/* Generated by scripts/generate_capabilities.py; edit capabilities/engines.json. */
#if (defined(ADDONS)) && (defined(LYAFORESTMPI))
if (strcmp(method_str, "lya-2pcf-mpi") == 0) *method_int = 185;
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTMPI))
if (strcmp(method_str, "lya-3pcf-mpi") == 0) *method_int = 186;
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTMPI))
if (strcmp(method_str, "lya-2pcf-3pcf-mpi") == 0) *method_int = 187;
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTMPI))
if (strcmp(method_str, "lya-1d-2pcf-mpi") == 0) *method_int = 188;
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTMPI))
if (strcmp(method_str, "lya-1d-3pcf-mpi") == 0) *method_int = 189;
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTMPI))
if (strcmp(method_str, "lya-1d-2pcf-3pcf-mpi") == 0) *method_int = 190;
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTMPI))
if (strcmp(method_str, "lya-1d-tree-2pcf-mpi") == 0) *method_int = 191;
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTMPI))
if (strcmp(method_str, "lya-1d-tree-3pcf-mpi") == 0) *method_int = 194;
#endif
