/* Generated by scripts/generate_capabilities.py; edit capabilities/engines.json. */
#if (defined(ADDONS)) && (defined(BALLTREESHEARSPHERE2BALLSOMP))
if (strcmp(method_str, "balltree-shear-sphere-2balls-omp") == 0) *method_int = 202;
#endif
