/* Generated by scripts/generate_capabilities.py; edit capabilities/engines.json. */
#if (defined(ADDONS)) && (defined(OCTREESHEARSPHEREOMP))
if (strcmp(method_str, "octree-shear-sphere-omp") == 0) *method_int = 199;
#endif
