/* Generated by scripts/generate_capabilities.py; edit capabilities/engines.json. */
#if (defined(ADDONS)) && (defined(LYAFORESTOMP))
if (strcmp(method_str, "lya-2pcf-omp") == 0) *method_int = 169;
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTOMP))
if (strcmp(method_str, "lya-3pcf-omp") == 0) *method_int = 170;
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTOMP))
if (strcmp(method_str, "lya-2pcf-3pcf-omp") == 0) *method_int = 171;
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTOMP))
if (strcmp(method_str, "lya-los-tree-2pcf-omp") == 0) *method_int = 206;
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTOMP))
if (strcmp(method_str, "lya-los-tree-3pcf-omp") == 0) *method_int = 207;
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTOMP))
if (strcmp(method_str, "lya-los-tree-2pcf-3pcf-omp") == 0) *method_int = 208;
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTOMP))
if (strcmp(method_str, "lya-1d-2pcf-omp") == 0) *method_int = 180;
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTOMP))
if (strcmp(method_str, "lya-1d-3pcf-omp") == 0) *method_int = 181;
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTOMP))
if (strcmp(method_str, "lya-1d-2pcf-3pcf-omp") == 0) *method_int = 182;
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTOMP))
if (strcmp(method_str, "lya-1d-tree-2pcf-omp") == 0) *method_int = 183;
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTOMP))
if (strcmp(method_str, "lya-1d-tree-3pcf-omp") == 0) *method_int = 193;
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTOMP))
if (strcmp(method_str, "lya-1d-tree-same-los-2pcf-omp") == 0) *method_int = 195;
#endif
