/* Generated by scripts/generate_capabilities.py; edit capabilities/engines.json. */
#if (defined(ADDONS)) && (defined(OCTREESHEARSPHERE2BALLSMPI))
if (strcmp(method_str, "octree-shear-sphere-2balls-mpi") == 0) *method_int = 203;
#endif
