/* Generated by scripts/generate_capabilities.py; edit capabilities/engines.json. */
#if (defined(ADDONS)) && (defined(OCTREEGGGMPI))
if (strcmp(method_str, "octree-ggg-mpi") == 0) *method_int = 172;
#endif
