#!/usr/bin/env python3
"""Generate engine registration, help, gate declarations and reference docs.

The JSON is the only editable engine catalogue. Generated files are checked in
so C consumers do not need Python at runtime. --check never rewrites files.
"""
import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = Path('capabilities/engines.json')


def enabled(expression, macros):
    """Evaluate the deliberately small defined()/boolean feature grammar."""
    expr = re.sub(r'defined\((\w+)\)', lambda m: '1' if m[1] in macros else '0', expression)
    if re.search(r'[^01()!&|\s]', expr):
        raise ValueError('unsupported capability condition: '+expression)
    # No arbitrary Python is admitted by the character and token checks.
    expr = expr.replace('&&', ' and ').replace('||', ' or ').replace('!', ' not ')
    return bool(eval(expr.strip(), {'__builtins__': {}}, {}))


def validate(data, root=ROOT):
    if data.get('schema_version') != 1:
        raise ValueError('unsupported capability schema')
    names=set()
    public_ids=set()
    for e in data['engines']:
        for name in [e['name'], *e['aliases']]:
            if not re.fullmatch(r'[a-zA-Z0-9_-]+', name) or name in names:
                raise ValueError('invalid or duplicate engine/alias: '+name)
            names.add(name)
        if type(e['id']) is not int or e['id'] < 0:
            raise ValueError('engine ID must be nonnegative')
        enabled(e['cpp'], set())
        for field in ('geometry','correlations','usage','sources','gate'):
            if not e.get(field): raise ValueError(f'{e["name"]}: missing {field}')
        gate=e['gate']
        for test in gate.get('tests', []):
            if not (root/test).is_file(): raise ValueError('missing declared test: '+test)
        if gate.get('oracle'):
            if e['id'] in public_ids: raise ValueError('duplicate public engine ID')
            public_ids.add(e['id'])
            if gate['oracle'] not in data['regression_groups'] or not gate.get('tests'):
                raise ValueError(e['name']+': oracle and tests must be declared together')
            if gate.get('parallel') not in ('omp','mpi'):
                raise ValueError(e['name']+': missing parallel declaration')
            for test in gate['tests']:
                if not (root/test).is_file(): raise ValueError('missing declared test: '+test)
        elif not gate.get('skip_reason'):
            raise ValueError(e['name']+': missing oracle or explicit coverage gap')
    return data


def render(data):
    banner='/* Generated by scripts/generate_capabilities.py; edit capabilities/engines.json. */\n'
    c=[banner, '#ifndef CBALLS_ENGINE_REGISTRY_H\n#define CBALLS_ENGINE_REGISTRY_H\n',
       'typedef struct { const char *name; int id; const char *geometry;\n'
       '    const char *correlations; const char *usage; } cballs_engine_capability;\n',
       'static const cballs_engine_capability cballs_engine_registry[] = {\n']
    aliases=[]
    for e in data['engines']:
        c += ['#if '+e['cpp']+'\n', '    {'+', '.join([json.dumps(e['name']),str(e['id']),
              *(json.dumps(e[k]) for k in ('geometry','correlations','usage'))])+'},\n', '#endif\n']
        for alias in e['aliases']:
            aliases += ['#if '+e['cpp']+'\n', '    {'+json.dumps(alias)+', '+str(e['id'])+'},\n','#endif\n']
    c += ['};\nstatic const struct { const char *name; int id; } cballs_engine_aliases[] = {\n',
          *aliases, '    {NULL, -1}\n};\n#endif\n']
    py=('# Generated by generate_capabilities.py; edit capabilities/engines.json.\n'
        'import json\nimport re\nfrom generate_capabilities import enabled\n'
        'CAPABILITIES = json.loads('+repr(json.dumps(data,sort_keys=True))+')\n'
        'ENGINES = {e["name"]: e for e in CAPABILITIES["engines"]}\n\n'
        'def expected_registry(settings):\n'
        '    macros = set(re.findall(r"-D(\\w+)", settings.get("CCFLAG", "")))\n'
        '    return {e["name"]: e["id"] for e in ENGINES.values() if enabled(e["cpp"], macros)}\n\n'
        'def gate_plan(registry):\n'
        '    rows = []\n'
        '    for name, identifier in registry.items():\n'
        '        e = ENGINES[name]\n'
        '        if identifier != e["id"] or not e["gate"].get("oracle"):\n'
        '            raise ValueError(name+": no matching retained public-gate oracle declaration")\n'
        '        rows.append(dict(engine=name, id=identifier, **e["gate"]))\n'
        '    return rows\n')
    doc=['# Engine capability catalogue\n\nGenerated from `capabilities/engines.json`. Do not edit this file.\n',
         '\nEngine registration, aliases, runtime help and the public gate use this same description. '
         'A legacy entry is not an accuracy or support claim. Enabling an entry without a retained oracle makes the public gate fail.\n']
    for e in data['engines']:
        doc += [f'\n## {e["name"]} (ID {e["id"]})\n\n',
                f'Build condition: `{e["cpp"]}`. Aliases: '+(', '.join(e['aliases']) or 'none')+'.\n\n',
                e['geometry']+'. '+e['correlations']+'.\n\n'+e['usage']+'\n\n',
                ('Public oracle: `'+e['gate']['oracle']+'`; tests: '+', '.join('`'+x+'`' for x in e['gate']['tests'])+'.\n')
                if e['gate'].get('oracle') else '**Coverage:** '+e['gate']['skip_reason']+'\n'+('\nAlternate reference tests: '+', '.join('`'+t+'`' for t in e['gate']['tests'])+'; build overrides: `'+json.dumps(e['gate']['test_profile'],sort_keys=True)+'`.\n' if e['gate'].get('test_profile') else '')]
    outputs = {Path('include/engine_registry_generated.h'):''.join(c),
               Path('scripts/capabilities_generated.py'):py,
               Path('ENGINE_CAPABILITIES.md'):''.join(doc)}
    # Keep legacy addon sockets usable without a second editable registry.
    fragments = {}
    for e in data['engines']:
        if e['registration_header']:
            row = fragments.setdefault(Path(e['registration_header']), [banner])
            row += ['#if '+e['cpp']+'\n']
            row += ['if (strcmp(method_str, '+json.dumps(name)+') == 0) *method_int = '+str(e['id'])+';\n'
                    for name in [e['name'], *e['aliases']]]
            row += ['#endif\n']
    outputs.update({path: ''.join(rows) for path, rows in fragments.items()})
    return outputs


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    data=validate(json.loads((ROOT/MANIFEST).read_text()))
    stale=[]
    for path,content in render(data).items():
        target=ROOT/path
        if not target.exists() or target.read_text()!=content:
            if args.check: stale.append(str(path))
            else: target.write_text(content)
    if stale: raise SystemExit('stale capability outputs: '+', '.join(stale)+'; run scripts/generate_capabilities.py')
    print(f'PASS: {len(data["engines"])} capability declarations and generated outputs')


if __name__=='__main__': main()
