/* Generated by scripts/generate_capabilities.py; edit capabilities/engines.json. */
#if (defined(ADDONS)) && (defined(KDTREESHEARSPHERE2BALLSOMP))
if (strcmp(method_str, "kdtree-shear-sphere-2balls-omp") == 0) *method_int = 201;
#endif
