/* Generated by scripts/generate_capabilities.py; edit capabilities/engines.json. */
#if (defined(ADDONS)) && (defined(OCTREE3PCF3DOMP))
if (strcmp(method_str, "octree-3pcf-3d-omp") == 0) *method_int = 166;
if (strcmp(method_str, "octree-ggg-3d-omp") == 0) *method_int = 166;
#endif
