/* Generated by scripts/generate_capabilities.py; edit capabilities/engines.json. */
#ifndef CBALLS_ENGINE_REGISTRY_H
#define CBALLS_ENGINE_REGISTRY_H
typedef struct { const char *name; int id; const char *geometry;
    const char *correlations; const char *usage; } cballs_engine_capability;
static const cballs_engine_capability cballs_engine_registry[] = {
#if 1
    {"octree-sincos-omp", 24, "2D/3D scalar; octree; OpenMP", "standard 2PCF and sine/cosine 3PCF multipoles", "Core method. Select KKKCorrelation for convergence 3PCF output. With SMOOTHPIVOTON=1, pivot smoothing is on by default; use no-smooth-pivot to disable it."},
#endif
#if (defined(ADDONS)) && (defined(KDTREE2BALLSOMP))
    {"kdtree-2balls-omp", 197, "scalar; median k-d tree; dual-node dual-node OpenMP scan", "2PCF and LogMultipole angular 3PCF, masks, and complex edge correction", "Enable KDTREE2BALLSOMPON=1. Two-node same-bin acceptance is the default; dual-node-bin-slop enables dual-node's bin-position slop and no-two-balls forces exact bodies. legacy-one-ball dispatches to the actual kdtree-omp kernel; there no-one-ball, smoothing, masks, order selection, and edge correction have the same meaning as for search=kdtree-omp. only-2pcf and only-3pcf select runtime work. nsmooth is the leaf capacity. BALLS4SCANLEVON=1 raises the minimum balanced KD frontier to 64 tasks. read-mask excludes masked bodies. With SMOOTHPIVOTON=1, an independent active-pivot tree uses smoothed pivot fields by default; use no-smooth-pivot to disable it."},
#endif
#if (defined(ADDONS)) && (defined(KDTREE2BALLSMPI))
    {"kdtree-2balls-mpi", 198, "scalar; median k-d tree; deterministic MPI+OpenMP dual-node scan", "distributed 2PCF and LogMultipole angular 3PCF, masks, and complex edge correction", "Enable KDTREE2BALLSMPION=1 and run with mpiexec; numberThreads is per rank. It accepts the kdtree-2balls-omp runtime controls. legacy-one-ball uses the distributed legacy KD kernel, and dual-node-direct-triples distributes the validation frontier; the latter still requires no-smooth-pivot. BALLS4SCANLEVON=1 sizes the balanced KD frontier for ranks times threads with a 64-task minimum. Ranks own deterministic frontier tasks, reduce raw histograms, and only rank 0 normalizes and writes output."},
#endif
#if (defined(ADDONS)) && (defined(BALLTREE2BALLSOMP))
    {"balltree-2balls-omp", 174, "scalar; FCFC PCA ball tree; dual-node dual/triple-node OpenMP scan", "2PCF and angular-multipole 3PCF with auto- and cross-catalog support", "TWOPCFON and TPCFON switch 2PCF and 3PCF independently; only-2pcf and only-3pcf select runtime work. Auto-correlations use a two-entry content-keyed cache whose packed points retain no body/Python pointers, so repeated 2PCFs and 3PCFs may reuse the compact tree; no-balltree-tree-cache forces cold construction. The production 3PCF inherits bounded sparse unresolved neighbor-node lists without copying multipole scratch; no-balltree-persistent-frontier restores a root restart for profiling. Deterministic upper-tree PCA statistics and sphere passes build in parallel; no-balltree-parallel-build selects the serial diagnostic path. dual-node-profile reports cache and native phases. Two-node acceptance is the default; dual-node-bin-slop enables bin-position slop, no-two-balls forces exact bodies, and dual-node-direct-triples retains the cubic validation traversal. nsmooth sets PCA-tree leaf capacity; dual-node-singleton-leaves and dual-node-bucket-leaves override the adaptive 2PCF leaf policy. legacy-one-ball dispatches to balltree-omp and rejects edge-corrections. Masks, weights, smoothing, and BALLS4SCANLEV remain supported; edge correction uses the native two-ball mode."},
#endif
#if (defined(ADDONS)) && (defined(BALLTREE2BALLSMPI))
    {"balltree-2balls-mpi", 179, "scalar; FCFC PCA ball tree; deterministic MPI+OpenMP dual/triple-node scan", "distributed 2PCF and angular-multipole 3PCF with auto- and cross-catalog support", "Build with BALLTREE2BALLSMPION=1 and run with mpiexec. It distributes the production body-pivot LogMultipole traversal and otherwise matches balltree-2balls-omp, including masks, smoothing, edge correction, order selectors, and BALLS4SCANLEV. legacy-one-ball dispatches to the privately linked distributed balltree legacy kernel. dual-node-direct-triples remains an OpenMP-only validation oracle."},
#endif
#if (defined(ADDONS)) && (defined(OCTREE2BALLSOMP))
    {"octree-2balls-omp", 176, "scalar; native octree; dual-node 2PCF and LogMultipole 3PCF", "2PCF and angular-multipole 3PCF with auto- and cross-catalog support", "Build with OCTREE2BALLSOMPON=1. TWOPCFON and TPCFON switch correlation orders; only-2pcf and only-3pcf select one in native two-ball mode. nsmooth bounds compact native-octree leaf occupancy. Conservative same-bin containment is the default 2PCF policy; dual-node-bin-slop selects dual-node-compatible Log/Linear near-bin acceptance, while no-two-balls selects exact body pairs. BALLS4SCANLEVON=1 supplies balanced frontiers. Normal mode stops tree preparation after production cell aggregation and does not use smooth pivots. legacy-one-ball instead builds the full threaded native octree and dispatches to the actual octree-GGG kernel, preserving behavior-ball/no-one-ball, masks, normalization, edge correction, ggg-profile, and SMOOTHPIVOTON/no-smooth-pivot behavior; only-3pcf and two-ball-specific controls are rejected in compatibility mode. read-mask accepts a FITS companion mask, columns-ascii-all/binary-all mask values, or set_catalog(mask=...) in cyballs."},
#endif
#if (defined(ADDONS)) && (defined(OCTREE2BALLSMPI))
    {"octree-2balls-mpi", 177, "scalar; native octree; deterministic MPI+OpenMP frontier", "distributed 2PCF and LogMultipole angular-multipole 3PCF", "Build with OCTREE2BALLSMPION=1 and run with mpiexec. numberThreads sets OpenMP threads per rank. Native two-ball mode accepts the octree-2balls-omp controls, including read-mask with valid-body-only normalization, except dual-node-direct-triples, which remains a serial validation oracle. legacy-one-ball instead builds the full threaded native octree and dispatches to the distributed octree-GGG kernel, preserving behavior-ball/no-one-ball, masks, normalization, edge correction, ggg-profile, and SMOOTHPIVOTON/no-smooth-pivot behavior; only-3pcf and two-ball-specific controls are rejected in compatibility mode. With BALLS4SCANLEVON=1, the selected backend builds its balanced adaptive frontier. Only rank 0 normalizes and writes output."},
#endif
#if (defined(ADDONS)) && (defined(OCTREESHEARSPHERE2BALLSOMP))
    {"octree-shear-sphere-2balls-omp", 200, "full-sky spin-2 shear; dual-node/Jarvis dual-node octree; OpenMP", "xi+/xi- and four Gamma-x shear 3PCF components", "Build with OCTREESHEARSPHERE2BALLSOMPON=1. The native 2PCF uses combined node radii, bin-width opening tests, dual-node's 0.585 split heuristic, simultaneous splitting of comparable nodes, and a chunked symmetric dual-tree frontier. no-two-balls or no-one-ball forces exact body pairs. only-2pcf runs only the dual-node scan; in a combined run the pair scan is separate and the spherical LogMultipole pivot scan computes only the 3PCF. only-3pcf skips pair work. With BALLS4SCANLEVON=1, a work-estimated native pivot-cell frontier conservatively prefilters neighbor roots, dynamically schedules exact body pivots, and merges task-local histograms in spatial order under a bounded memory budget. The experimental shear-pivot-reuse option instead inherits unresolved neighbors and partial rings and permits aggregate pivots; CBALLS_SHEAR_PIVOT_TOL controls its spherical phase budget and requires numerical calibration. It requires no-smooth-pivot and is off by default. Body unit vectors are reused while native aggregate-cell centers remain explicitly normalized. legacy-one-ball dispatches this search name to the actual octree-shear-sphere-omp kernel. Use no-smooth-pivot to make the unsmoothed pair paths available. Set CBALLS_SHEAR_PROFILE=1 for kernel timings."},
#endif
#if (defined(ADDONS)) && (defined(KDTREESHEARSPHERE2BALLSOMP))
    {"kdtree-shear-sphere-2balls-omp", 201, "full-sky spin-2 shear; dual-node/Jarvis median KD tree; OpenMP", "xi+/xi- and four Gamma-x shear 3PCF components", "Build with KDTREESHEARSPHERE2BALLSOMPON=1. KD nodes store first and second spin-2 moments in their local tangent frames. only-2pcf uses a symmetric dual-node scan; only-3pcf uses exact body pivots and accepted KD neighbor nodes. With BALLS4SCANLEVON=1, a work-estimated pivot-cell frontier dynamically schedules 3PCF work, conservatively prefilters neighbor roots, and merges task-local histograms in spatial order under a bounded memory budget. Catalog positions are normalized once and reused by the SIMD-friendly transport/ring kernel. no-two-balls or no-one-ball forces exact bodies, dual-node-bin-slop enables the looser radial criterion, and nsmooth sets leaf capacity. Masks, mode-coupling edge correction, and the safe SMOOTHPIVOTON/no-smooth-pivot contract match the spherical octree shear engines. Set CBALLS_SHEAR_PROFILE=1 for kernel timings."},
#endif
#if (defined(ADDONS)) && (defined(BALLTREESHEARSPHERE2BALLSOMP))
    {"balltree-shear-sphere-2balls-omp", 202, "full-sky spin-2 shear; dual-node/Jarvis FCFC PCA ball tree; OpenMP", "xi+/xi- and four Gamma-x shear 3PCF components", "Build with BALLTREESHEARSPHERE2BALLSOMPON=1. PCA-split nodes carry conservative spherical balls and direct first/second spin-2 moments. Construction skips leaf PCA, fuses center/PCA statistics, and parallelizes upper member passes with fixed chunks and exact preorder node ranges; no-balltree-parallel-build selects serial construction with identical chunking. Unsmoothed repeated roles share one tree within a call, without a cross-call cache. The symmetric dual-node 2PCF projects both shears onto their connecting great circle and combines auto-pair orientations. The default 3PCF uses exact body pivots. With BALLS4SCANLEVON=1, opt-in shear-pivot-reuse inherits sparse unresolved lists and ancestor-frame rings, permitting aggregate pivots under CBALLS_SHEAR_PIVOT_TOL; calibrate this spherical phase budget against exact results. It requires no-smooth-pivot, has a 64 MiB per-worker scratch cap, and does not change the 2PCF. The work-estimated frontier publishes histograms in spatial order under a 256 MiB cap. Either no-one-ball or no-two-balls disables cell aggregation for both statistics. dual-node-bin-slop enables the looser radial criterion; nsmooth sets leaf capacity. Masks, mode-coupling correction, and smoothing contracts match the other spherical shear engines. CBALLS_SHEAR_PROFILE=1 reports build, kernel, and reuse counters."},
#endif
#if (defined(ADDONS)) && (defined(KDTREEBOXOMP))
    {"kdtree-box-omp", 71, "periodic Cartesian box; k-d tree; OpenMP", "box 2PCF", "Use usePeriodic=true; cute-box-fmt writes CUTE-compatible output. BALLS4SCANLEVON=1 scans a balanced, spatially ordered KD pivot frontier."},
#endif
#if (defined(ADDONS)) && (defined(NEIGHBORBOXESOMP))
    {"neighbor-boxes-omp", 73, "periodic Cartesian box; linked boxes; OpenMP", "periodic pair counts and unweighted density correlation function", "Use usePeriodic=true. Coordinates are wrapped locally modulo lengthBox; centered and translated periodic catalogs are accepted. This method does not accumulate a convergence-weighted 2PCF. With SMOOTHPIVOTON=1, pivot smoothing is on by default; use no-smooth-pivot to disable it."},
#endif
#if (defined(ADDONS)) && (defined(OCTREE3PCF3DOMP))
    {"octree-3pcf-3d-omp", 166, "3D scalar; exact octree leaves; OpenMP", "spherical-harmonic 2PCF/3PCF multipoles", "Use x,y,z,delta,weight input. compute-2pcf-3d and compute-3pcf-3d select outputs. BALLS4SCANLEVON=1 preserves exact body pivots and forms fixed reduction blocks from a spatial scan-level order. For Lyman-alpha input, exclude-all-same-los requires three distinct forest IDs per triplet; octree-ggg-3d-omp is an alias."},
#endif
#if (defined(ADDONS)) && (defined(OCTREE3PCF3DMPI))
    {"octree-3pcf-3d-mpi", 192, "3D scalar; exact octree leaves; MPI+OpenMP pivot blocks", "spherical-harmonic 2PCF/3PCF; data/random survey estimator and edge correction", "Enable OCTREE3PCF3DMPION=1 and run with mpiexec. compute-2pcf-3d and compute-3pcf-3d select outputs. BALLS4SCANLEVON=1 distributes fixed blocks of the spatial exact-body pivot order across ranks. For Lyman-alpha input, exclude-all-same-los requires three distinct forest IDs per triplet. survey-estimator-3d uses data,random catalogs with iCatalogs=1,2. Catalogs are replicated; numberThreads is per rank. octree-ggg-3d-mpi is an alias."},
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTOMP))
    {"lya-2pcf-omp", 169, "3D Lyman-alpha forest pixels; exact octree leaves; OpenMP", "weighted anisotropic 2PCF", "Requires one forest catalog, non-periodic geometry, and forest IDs; see input below."},
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTOMP))
    {"lya-3pcf-omp", 170, "3D Lyman-alpha forest pixels; exact octree leaves; OpenMP", "weighted five-dimensional 3PCF", "Requires one forest catalog, non-periodic geometry, and forest IDs; see input below."},
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTOMP))
    {"lya-2pcf-3pcf-omp", 171, "3D Lyman-alpha forest pixels; exact octree leaves; OpenMP", "weighted 2PCF and 3PCF in one traversal", "Requires one forest catalog, non-periodic geometry, and forest IDs; see input below."},
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTOMP))
    {"lya-los-tree-2pcf-omp", 206, "3D forest discovery + per-LOS radial trees; OpenMP", "exact weighted anisotropic 2PCF", "One pixel discovers each neighboring forest; excludes the pivot forest. Same domain, bins and output as lya-2pcf-omp; transverse separation is retained."},
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTOMP))
    {"lya-los-tree-3pcf-omp", 207, "3D forest discovery + per-LOS radial trees; OpenMP", "exact weighted five-dimensional 3PCF", "Same domain, bins and output as lya-3pcf-omp; all three forest IDs must differ. No angular or cell approximation."},
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTOMP))
    {"lya-los-tree-2pcf-3pcf-omp", 208, "3D forest discovery + per-LOS radial trees; OpenMP", "exact weighted 2PCF and 3PCF in one discovery pass", "Uses the larger discovery sphere, then each estimator's exact cuts. Not a radial-only estimator. Enabled by LYAFORESTOMPON=1."},
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTOMP))
    {"lya-1d-2pcf-omp", 180, "radial Lyman-alpha pixels; sorted 1D range scan; OpenMP", "weighted radial-only 2PCF", "Ignores transverse separation; lya2RpMax and lya2RpBins define |delta radial distance| bins."},
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTOMP))
    {"lya-1d-3pcf-omp", 181, "radial Lyman-alpha pixels; sorted 1D range scan; OpenMP", "weighted radial-only 3PCF", "Ignores transverse separation; lya3RMax and lya3RBins define signed pivot-lag bins."},
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTOMP))
    {"lya-1d-2pcf-3pcf-omp", 182, "radial Lyman-alpha pixels; sorted 1D range scan; OpenMP", "weighted radial-only 2PCF and 3PCF", "Requires forest IDs; all correlated pixels must belong to distinct quasars."},
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTOMP))
    {"lya-1d-tree-2pcf-omp", 183, "radial Lyman-alpha pixels; exact 1D interval tree; OpenMP", "weighted radial-only 2PCF", "Uses exact same-bin node aggregation and subtracts within-quasar pairs; lya2RpMax and lya2RpBins set the domain."},
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTOMP))
    {"lya-1d-tree-3pcf-omp", 193, "radial Lyman-alpha pixels; exact 1D interval tree; OpenMP", "weighted radial-only 3PCF", "Uses signed-lag node moments and exact same-forest neighbor-pair subtraction; lya3RMax and lya3RBins set the two-axis domain. LYA1D_TREE3_LEAF_SIZE is reported by make-info."},
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTOMP))
    {"lya-1d-tree-same-los-2pcf-omp", 195, "per-LOS radial Lyman-alpha pixels; exact 1D interval trees; OpenMP", "equal-LOS mean of weighted within-forest radial 2PCFs", "Builds one radial interval tree per forest, accepts pairs only when both pixels share forest_id, normalizes each forest histogram separately, then averages occupied forests with equal weight per bin. Uses lya2RpMax and lya2RpBins."},
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTMPI))
    {"lya-2pcf-mpi", 185, "Lyman-alpha pixels; 3D octree; MPI+OpenMP", "weighted anisotropic 2PCF", "Enable LYAFORESTMPION=1; run with mpiexec and numberThreads per rank. Requires one forest catalog (file or in-memory, see below), DEFDIMENSION=3, and usePeriodic=false. Options and output columns match lya-2pcf-omp. Raw sums are reduced before normalization; only rank 0 writes."},
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTMPI))
    {"lya-3pcf-mpi", 186, "Lyman-alpha pixels; 3D octree; MPI+OpenMP", "weighted five-dimensional 3PCF", "Enable LYAFORESTMPION=1; run with mpiexec and numberThreads per rank. Requires one forest catalog (file or in-memory, see below), DEFDIMENSION=3, and usePeriodic=false. Options and output columns match lya-3pcf-omp. Raw sums are reduced before normalization; only rank 0 writes."},
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTMPI))
    {"lya-2pcf-3pcf-mpi", 187, "Lyman-alpha pixels; 3D octree; MPI+OpenMP", "weighted 2PCF and 3PCF", "Enable LYAFORESTMPION=1; run with mpiexec and numberThreads per rank. Requires one forest catalog (file or in-memory, see below), DEFDIMENSION=3, and usePeriodic=false. Options and output columns match lya-2pcf-3pcf-omp. Raw sums are reduced before normalization; only rank 0 writes."},
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTMPI))
    {"lya-1d-2pcf-mpi", 188, "Lyman-alpha pixels; radial range scan; MPI+OpenMP", "weighted radial-only 2PCF", "Enable LYAFORESTMPION=1; run with mpiexec and numberThreads per rank. Requires one forest catalog (file or in-memory, see below), DEFDIMENSION=3, and usePeriodic=false. Options and output columns match lya-1d-2pcf-omp. Raw sums are reduced before normalization; only rank 0 writes."},
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTMPI))
    {"lya-1d-3pcf-mpi", 189, "Lyman-alpha pixels; radial range scan; MPI+OpenMP", "weighted radial-only 3PCF", "Enable LYAFORESTMPION=1; run with mpiexec and numberThreads per rank. Requires one forest catalog (file or in-memory, see below), DEFDIMENSION=3, and usePeriodic=false. Options and output columns match lya-1d-3pcf-omp. Raw sums are reduced before normalization; only rank 0 writes."},
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTMPI))
    {"lya-1d-2pcf-3pcf-mpi", 190, "Lyman-alpha pixels; radial range scan; MPI+OpenMP", "weighted radial-only 2PCF and 3PCF", "Enable LYAFORESTMPION=1; run with mpiexec and numberThreads per rank. Requires one forest catalog (file or in-memory, see below), DEFDIMENSION=3, and usePeriodic=false. Options and output columns match lya-1d-2pcf-3pcf-omp. Raw sums are reduced before normalization; only rank 0 writes."},
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTMPI))
    {"lya-1d-tree-2pcf-mpi", 191, "Lyman-alpha pixels; radial interval tree; MPI+OpenMP", "weighted radial-only 2PCF with same-forest subtraction", "Enable LYAFORESTMPION=1; run with mpiexec and numberThreads per rank. Requires one forest catalog (file or in-memory, see below), DEFDIMENSION=3, and usePeriodic=false. Options and output columns match lya-1d-tree-2pcf-omp. Raw sums are reduced before normalization; only rank 0 writes."},
#endif
#if (defined(ADDONS)) && (defined(LYAFORESTMPI))
    {"lya-1d-tree-3pcf-mpi", 194, "Lyman-alpha pixels; radial interval tree; MPI+OpenMP", "weighted radial-only 3PCF with exact three-forest exclusion", "Enable LYAFORESTMPION=1; run with mpiexec and numberThreads per rank. Options and output columns match lya-1d-tree-3pcf-omp. Pivot blocks and raw long-double sums are distributed; only rank 0 normalizes and writes. LYA1D_TREE3_LEAF_SIZE is reported by make-info."},
#endif
};
static const struct { const char *name; int id; } cballs_engine_aliases[] = {
#if (defined(ADDONS)) && (defined(OCTREE3PCF3DOMP))
    {"octree-ggg-3d-omp", 166},
#endif
#if (defined(ADDONS)) && (defined(OCTREE3PCF3DMPI))
    {"octree-ggg-3d-mpi", 192},
#endif
    {NULL, -1}
};
#endif
