/* Generated by scripts/generate_capabilities.py; edit capabilities/engines.json. */
#if (defined(ADDONS)) && (defined(OCTREE3PCF3DMPI))
if (strcmp(method_str, "octree-3pcf-3d-mpi") == 0) *method_int = 192;
if (strcmp(method_str, "octree-ggg-3d-mpi") == 0) *method_int = 192;
#endif
