/* Generated by scripts/generate_capabilities.py; edit capabilities/engines.json. */
#if (defined(ADDONS)) && (defined(OCTREE2BALLSMPI))
if (strcmp(method_str, "octree-2balls-mpi") == 0) *method_int = 177;
#endif
