/* Generated by scripts/generate_capabilities.py; edit capabilities/engines.json. */
#if (defined(ADDONS)) && (defined(OCTREE2BALLSOMP))
if (strcmp(method_str, "octree-2balls-omp") == 0) *method_int = 176;
#endif
